#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMSApplication.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="SMSRecords")]
	public partial class DataClassesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertSMS(SMS instance);
    partial void UpdateSMS(SMS instance);
    partial void DeleteSMS(SMS instance);
    #endregion
		
		public DataClassesDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["SMSRecordsConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<SMS> SMS
		{
			get
			{
				return this.GetTable<SMS>();
			}
		}
		
		public System.Data.Linq.Table<Statistics> Statistics
		{
			get
			{
				return this.GetTable<Statistics>();
			}
		}
		
		public System.Data.Linq.Table<Country> Country
		{
			get
			{
				return this.GetTable<Country>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SMS")]
	public partial class SMS : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _SmsID;
		
		private int _MobileCountryCode;
		
		private string _FromSender;
		
		private string _ToReciever;
		
		private double _Price;
		
		private string _State;
		
		private int _CountryID;
		
		private System.Nullable<System.DateTime> _dateTime;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSmsIDChanging(int value);
    partial void OnSmsIDChanged();
    partial void OnMobileCountryCodeChanging(int value);
    partial void OnMobileCountryCodeChanged();
    partial void OnFromSenderChanging(string value);
    partial void OnFromSenderChanged();
    partial void OnToRecieverChanging(string value);
    partial void OnToRecieverChanged();
    partial void OnPriceChanging(double value);
    partial void OnPriceChanged();
    partial void OnStateChanging(string value);
    partial void OnStateChanged();
    partial void OnCountryIDChanging(int value);
    partial void OnCountryIDChanged();
    partial void OndateTimeChanging(System.Nullable<System.DateTime> value);
    partial void OndateTimeChanged();
    #endregion
		
		public SMS()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SmsID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int SmsID
		{
			get
			{
				return this._SmsID;
			}
			set
			{
				if ((this._SmsID != value))
				{
					this.OnSmsIDChanging(value);
					this.SendPropertyChanging();
					this._SmsID = value;
					this.SendPropertyChanged("SmsID");
					this.OnSmsIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MobileCountryCode", DbType="Int NOT NULL")]
		public int MobileCountryCode
		{
			get
			{
				return this._MobileCountryCode;
			}
			set
			{
				if ((this._MobileCountryCode != value))
				{
					this.OnMobileCountryCodeChanging(value);
					this.SendPropertyChanging();
					this._MobileCountryCode = value;
					this.SendPropertyChanged("MobileCountryCode");
					this.OnMobileCountryCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FromSender", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string FromSender
		{
			get
			{
				return this._FromSender;
			}
			set
			{
				if ((this._FromSender != value))
				{
					this.OnFromSenderChanging(value);
					this.SendPropertyChanging();
					this._FromSender = value;
					this.SendPropertyChanged("FromSender");
					this.OnFromSenderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ToReciever", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string ToReciever
		{
			get
			{
				return this._ToReciever;
			}
			set
			{
				if ((this._ToReciever != value))
				{
					this.OnToRecieverChanging(value);
					this.SendPropertyChanging();
					this._ToReciever = value;
					this.SendPropertyChanged("ToReciever");
					this.OnToRecieverChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Price", DbType="Float NOT NULL")]
		public double Price
		{
			get
			{
				return this._Price;
			}
			set
			{
				if ((this._Price != value))
				{
					this.OnPriceChanging(value);
					this.SendPropertyChanging();
					this._Price = value;
					this.SendPropertyChanged("Price");
					this.OnPriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_State", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string State
		{
			get
			{
				return this._State;
			}
			set
			{
				if ((this._State != value))
				{
					this.OnStateChanging(value);
					this.SendPropertyChanging();
					this._State = value;
					this.SendPropertyChanged("State");
					this.OnStateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CountryID", DbType="Int NOT NULL")]
		public int CountryID
		{
			get
			{
				return this._CountryID;
			}
			set
			{
				if ((this._CountryID != value))
				{
					this.OnCountryIDChanging(value);
					this.SendPropertyChanging();
					this._CountryID = value;
					this.SendPropertyChanged("CountryID");
					this.OnCountryIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dateTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> dateTime
		{
			get
			{
				return this._dateTime;
			}
			set
			{
				if ((this._dateTime != value))
				{
					this.OndateTimeChanging(value);
					this.SendPropertyChanging();
					this._dateTime = value;
					this.SendPropertyChanged("dateTime");
					this.OndateTimeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[Statistics]")]
	public partial class Statistics
	{
		
		private System.DateTime _Day;
		
		private int _MCC;
		
		private double _pricePerSMS;
		
		private int _count;
		
		private double _totalPrice;
		
		public Statistics()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Day", DbType="DateTime NOT NULL")]
		public System.DateTime Day
		{
			get
			{
				return this._Day;
			}
			set
			{
				if ((this._Day != value))
				{
					this._Day = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MCC", DbType="Int NOT NULL")]
		public int MCC
		{
			get
			{
				return this._MCC;
			}
			set
			{
				if ((this._MCC != value))
				{
					this._MCC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pricePerSMS", DbType="Float NOT NULL")]
		public double pricePerSMS
		{
			get
			{
				return this._pricePerSMS;
			}
			set
			{
				if ((this._pricePerSMS != value))
				{
					this._pricePerSMS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_count", DbType="Int NOT NULL")]
		public int count
		{
			get
			{
				return this._count;
			}
			set
			{
				if ((this._count != value))
				{
					this._count = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_totalPrice", DbType="Float NOT NULL")]
		public double totalPrice
		{
			get
			{
				return this._totalPrice;
			}
			set
			{
				if ((this._totalPrice != value))
				{
					this._totalPrice = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Country")]
	public partial class Country
	{
		
		private int _MCC;
		
		private string _CC;
		
		private string _Name;
		
		private double _PricePerSMS;
		
		public Country()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MCC", DbType="Int NOT NULL")]
		public int MCC
		{
			get
			{
				return this._MCC;
			}
			set
			{
				if ((this._MCC != value))
				{
					this._MCC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CC", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string CC
		{
			get
			{
				return this._CC;
			}
			set
			{
				if ((this._CC != value))
				{
					this._CC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PricePerSMS", DbType="Float NOT NULL")]
		public double PricePerSMS
		{
			get
			{
				return this._PricePerSMS;
			}
			set
			{
				if ((this._PricePerSMS != value))
				{
					this._PricePerSMS = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
