<?xml version="1.0" encoding="utf-8"?><Database Name="SMSRecords" Class="DataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.\sqlExpress;Initial Catalog=SMSRecords;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="SMSRecordsConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.SMS" Member="SMS">
    <Type Name="SMS">
      <Column Name="SmsID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MobileCountryCode" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FromSender" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ToReciever" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Price" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="State" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CountryID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="dateTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.[Statistics]" Member="Statistics">
    <Type Name="Statistics">
      <Column Name="Day" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="MCC" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="pricePerSMS" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="count" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="totalPrice" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Country" Member="Country">
    <Type Name="Country">
      <Column Name="MCC" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CC" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="PricePerSMS" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>